name: "build"

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - env-alpine
          - env-android
          - env-archlinux
          - env-centos
          - env-debian
          - env-fedora
          - env-opensuse
          - env-sphinx
          - env-ubuntu
          - env-ubuntu-minimal
          - toolchain-aarch64-linux-gnu
          - toolchain-arm-bcm2708hardfp-linux-gnueabi
          - toolchain-arm-linux-gnueabihf
          - toolchain-linux-android

    name: ${{ matrix.image }}

    env:
      CACHE_FROM: /tmp/.buildx-cache
      CACHE_TO: /tmp/.buildx-cache-new

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_FROM }}
          key: ${{ matrix.image }}-${{ github.sha }}
          restore-keys: |
            ${{ matrix.image }}-

      - name: Setup buildx
        run: |
          docker buildx create --use

      - name: Setup env
        if: |
          github.repository_owner == 'roc-streaming' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main'
        run: |
          echo "ENABLE_PUSH=1" >> $GITHUB_ENV

      - name: Run docker
        run: |
          if [[ $ENABLE_PUSH = 1 ]]; then \
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            ./make.sh --push images/${{ matrix.image }}
          else
            ./make.sh images/${{ matrix.image }}
          fi

      - name: Move cache
        if: always()
        run: |
          rm -rf ${CACHE_FROM}
          mv ${CACHE_TO} ${CACHE_FROM}

      - name: Save cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ${{ env.CACHE_FROM }}
          key: ${{ matrix.image }}-${{ github.sha }}
